// Auto-generated by build-presets-qawaleb.mjs — do not edit directly
// Source JSON files: renderer/presets/<template-id>/*.json
window.QAWALEB_TEMPLATE_PRESETS_EXT = {
  "breaking-bold": [
    {
      "id": "bb-blue-formal",
      "label": "أزرق رسمي",
      "description": "أزرق داكن مناسب للتقارير الرسمية",
      "colors": {
        "background": "#0a0f1a",
        "surface": "#111827",
        "accent": "#1e56a0",
        "accentAlt": "#3b82f6",
        "text": "#f6f4ef",
        "muted": "#b0b8c8"
      },
      "scale": 0.95,
      "x": 0,
      "y": 0,
      "fontSize": 62,
      "quoteMark": false,
      "parallax": true,
      "cinematicBarSize": 6,
      "backgroundOpacity": 12,
      "backgroundBlur": 10,
      "backgroundRadius": 36,
      "backgroundFeather": 72,
      "effects": [
        "dust",
        "bokeh"
      ]
    },
    {
      "id": "bb-dark-minimal",
      "label": "داكن بسيط",
      "description": "مظهر داكن أنيق مع ألوان هادئة",
      "colors": {
        "background": "#0d0d0d",
        "surface": "#1a1a1a",
        "accent": "#c0a060",
        "accentAlt": "#d4b878",
        "text": "#f0ede8",
        "muted": "#a09a90"
      },
      "scale": 1,
      "x": 0,
      "y": 0,
      "fontSize": 63,
      "quoteMark": false,
      "parallax": false,
      "cinematicBarSize": 8,
      "backgroundOpacity": 8,
      "backgroundBlur": 14,
      "backgroundRadius": 48,
      "backgroundFeather": 96,
      "effects": [
        "bokeh"
      ]
    },
    {
      "id": "bb-red-alert",
      "label": "أحمر عاجل",
      "description": "أحمر قوي مناسب للأخبار العاجلة",
      "colors": {
        "background": "#0a0a0a",
        "surface": "#111111",
        "accent": "#e10600",
        "accentAlt": "#ff3322",
        "text": "#f6f4ef",
        "muted": "#d8d6d1"
      },
      "scale": 1,
      "x": 0,
      "y": 0,
      "fontSize": 65,
      "quoteMark": false,
      "parallax": true,
      "cinematicBarSize": 6,
      "backgroundOpacity": 10,
      "backgroundBlur": 12,
      "backgroundRadius": 42,
      "backgroundFeather": 84,
      "effects": [
        "dust",
        "light-leak"
      ]
    }
  ],
  "cinematic-dark": [
    {
      "id": "cd-cinematic-gold",
      "label": "ذهب سينمائي",
      "description": "الذهبي السينمائي الكلاسيكي",
      "colors": {
        "background": "#0d0d0d",
        "accent": "#d9a14a",
        "text": "#f5f3ee",
        "muted": "#a8a39a",
        "alert": "#e10600"
      },
      "scale": 1,
      "x": 0,
      "y": 0,
      "fontSize": 65,
      "quoteMark": false,
      "parallax": true,
      "cinematicBarSize": 6,
      "backgroundOpacity": 10,
      "backgroundBlur": 12,
      "backgroundRadius": 42,
      "backgroundFeather": 84,
      "effects": [
        "dust",
        "bokeh"
      ]
    },
    {
      "id": "cd-night-blue",
      "label": "أزرق ليلي",
      "description": "درجات زرقاء داكنة ليلية",
      "colors": {
        "background": "#0a0e1a",
        "accent": "#3a7bbd",
        "text": "#e8ecf4",
        "muted": "#8892a8",
        "alert": "#e10600"
      },
      "scale": 0.95,
      "x": 0,
      "y": 0,
      "fontSize": 63,
      "quoteMark": false,
      "parallax": true,
      "cinematicBarSize": 6,
      "backgroundOpacity": 12,
      "backgroundBlur": 10,
      "backgroundRadius": 36,
      "backgroundFeather": 72,
      "effects": [
        "bokeh",
        "light-leak"
      ]
    },
    {
      "id": "cd-silver-elegance",
      "label": "فضي جريء",
      "description": "فضي أنيق على خلفية داكنة",
      "colors": {
        "background": "#121214",
        "accent": "#b8bcc4",
        "text": "#f5f5f5",
        "muted": "#8a8a92",
        "alert": "#e10600"
      },
      "scale": 1,
      "x": 0,
      "y": 0,
      "fontSize": 64,
      "quoteMark": false,
      "parallax": false,
      "cinematicBarSize": 8,
      "backgroundOpacity": 8,
      "backgroundBlur": 14,
      "backgroundRadius": 48,
      "backgroundFeather": 96,
      "effects": [
        "dust"
      ]
    }
  ],
  "documentary-minimal": [
    {
      "id": "dm-doc-green",
      "label": "أخضر وثائقي",
      "description": "الخضرة الطبيعية للتقارير الوثائقية",
      "colors": {
        "background": "#f6f4ef",
        "line": "#d6d4cd",
        "accent": "#1a4d3e",
        "text": "#16161a",
        "muted": "#7a7a7e"
      },
      "scale": 1,
      "x": 0,
      "y": 0,
      "fontSize": 65,
      "quoteMark": true,
      "parallax": true,
      "cinematicBarSize": 6,
      "backgroundOpacity": 10,
      "backgroundBlur": 12,
      "backgroundRadius": 42,
      "backgroundFeather": 84,
      "effects": [
        "dust",
        "bokeh"
      ]
    },
    {
      "id": "dm-pure-white",
      "label": "أبيض نقي",
      "description": "مظهر نظيف بأبيض ناصع",
      "colors": {
        "background": "#ffffff",
        "line": "#e8e8ec",
        "accent": "#2a2a3a",
        "text": "#0a0a0a",
        "muted": "#707070"
      },
      "scale": 1,
      "x": 0,
      "y": 0,
      "fontSize": 64,
      "quoteMark": true,
      "parallax": false,
      "cinematicBarSize": 8,
      "backgroundOpacity": 8,
      "backgroundBlur": 14,
      "backgroundRadius": 48,
      "backgroundFeather": 96,
      "effects": [
        "dust",
        "bokeh"
      ]
    },
    {
      "id": "dm-warm-natural",
      "label": "دافئ طبيعي",
      "description": "ألوان دافئة طبيعية",
      "colors": {
        "background": "#f5f0e6",
        "line": "#e0d8c8",
        "accent": "#8d6e3a",
        "text": "#2a2018",
        "muted": "#807060"
      },
      "scale": 0.95,
      "x": 0,
      "y": 0,
      "fontSize": 63,
      "quoteMark": true,
      "parallax": true,
      "cinematicBarSize": 6,
      "backgroundOpacity": 12,
      "backgroundBlur": 10,
      "backgroundRadius": 36,
      "backgroundFeather": 72,
      "effects": [
        "dust"
      ]
    }
  ],
  "editorial-elegant": [
    {
      "id": "ee-cool-silver",
      "label": "فضي أنيق",
      "description": "درجات رمادية فضية عصرية",
      "colors": {
        "background": "#f0f0f2",
        "surface": "#e6e6ea",
        "accent": "#7a8a9a",
        "accentDark": "#5a6a7a",
        "text": "#1a1a2e",
        "muted": "#8a8a96"
      },
      "scale": 0.95,
      "x": 0,
      "y": 0,
      "fontSize": 63,
      "quoteMark": false,
      "parallax": true,
      "cinematicBarSize": 6,
      "backgroundOpacity": 12,
      "backgroundBlur": 10,
      "backgroundRadius": 36,
      "backgroundFeather": 72,
      "effects": [
        "dust"
      ]
    },
    {
      "id": "ee-deep-navy",
      "label": "كحلي كلاسيكي",
      "description": "مظهر جريء بألوان كحلية",
      "colors": {
        "background": "#0d1b2a",
        "surface": "#1b2838",
        "accent": "#c9a84c",
        "accentDark": "#a8882e",
        "text": "#f0ede8",
        "muted": "#8e8e96"
      },
      "scale": 1,
      "x": 0,
      "y": 0,
      "fontSize": 62,
      "quoteMark": false,
      "parallax": false,
      "cinematicBarSize": 8,
      "backgroundOpacity": 8,
      "backgroundBlur": 14,
      "backgroundRadius": 48,
      "backgroundFeather": 96,
      "effects": [
        "bokeh",
        "light-leak"
      ]
    },
    {
      "id": "ee-warm-gold",
      "label": "ذهبي دافئ",
      "description": "ألوان دافئة بلمسات ذهبية",
      "colors": {
        "background": "#f3eee2",
        "surface": "#ebe4d2",
        "accent": "#b08d57",
        "accentDark": "#8a6a3a",
        "text": "#10182b",
        "muted": "#7a6e58"
      },
      "scale": 1,
      "x": 0,
      "y": 0,
      "fontSize": 65,
      "quoteMark": false,
      "parallax": true,
      "cinematicBarSize": 6,
      "backgroundOpacity": 10,
      "backgroundBlur": 12,
      "backgroundRadius": 42,
      "backgroundFeather": 84,
      "effects": [
        "dust",
        "bokeh"
      ]
    }
  ],
  "facebook-animated": [
    {
      "id": "fb-clean-white",
      "label": "أبيض نقي",
      "description": "مظهر أبيض نظيف وبسيط",
      "colors": {
        "background": "#f0f2f5",
        "card": "#ffffff",
        "accent": "#1a6ed8",
        "border": "#dadde1",
        "text": "#1c1e21",
        "muted": "#606770"
      },
      "scale": 0.95,
      "x": 0,
      "y": 0,
      "fontSize": 64,
      "quoteMark": false,
      "parallax": false,
      "cinematicBarSize": 8,
      "backgroundOpacity": 12,
      "backgroundBlur": 10,
      "backgroundRadius": 36,
      "backgroundFeather": 72,
      "effects": [
        "dust"
      ]
    },
    {
      "id": "fb-dark-mode",
      "label": "داكن",
      "description": "وضع داكن لمنشورات فيسبوك",
      "colors": {
        "background": "#18191a",
        "card": "#242526",
        "accent": "#2d88ff",
        "border": "#3e4042",
        "text": "#e4e6eb",
        "muted": "#b0b3b8"
      },
      "scale": 1,
      "x": 0,
      "y": 0,
      "fontSize": 63,
      "quoteMark": false,
      "parallax": true,
      "cinematicBarSize": 6,
      "backgroundOpacity": 8,
      "backgroundBlur": 14,
      "backgroundRadius": 48,
      "backgroundFeather": 96,
      "effects": [
        "bokeh",
        "light-leak"
      ]
    },
    {
      "id": "fb-facebook-blue",
      "label": "أزرق فيسبوك",
      "description": "أزرق فيسبوك الكلاسيكي",
      "colors": {
        "background": "#ccd0d5",
        "card": "#ffffff",
        "accent": "#1877f2",
        "border": "#ced0d4",
        "text": "#050505",
        "muted": "#65676b"
      },
      "scale": 1,
      "x": 0,
      "y": 0,
      "fontSize": 65,
      "quoteMark": false,
      "parallax": true,
      "cinematicBarSize": 6,
      "backgroundOpacity": 10,
      "backgroundBlur": 12,
      "backgroundRadius": 42,
      "backgroundFeather": 84,
      "effects": [
        "dust",
        "bokeh"
      ]
    }
  ],
  "instagram-animated": [
    {
      "id": "ig-dark-elegant",
      "label": "داكن أنيق",
      "description": "مظهر داكن أنيق",
      "colors": {
        "background": "#121212",
        "card": "#1e1e1e",
        "accent": "#e1306c",
        "border": "#2a2a2a",
        "text": "#f5f5f5",
        "muted": "#a0a0a0"
      },
      "scale": 0.95,
      "x": 0,
      "y": 0,
      "fontSize": 63,
      "quoteMark": false,
      "parallax": true,
      "cinematicBarSize": 6,
      "backgroundOpacity": 8,
      "backgroundBlur": 14,
      "backgroundRadius": 48,
      "backgroundFeather": 96,
      "effects": [
        "bokeh",
        "light-leak"
      ]
    },
    {
      "id": "ig-instagram-pink",
      "label": "وردي إنستغرام",
      "description": "الوردي المميز لإنستغرام",
      "colors": {
        "background": "#fafafa",
        "card": "#ffffff",
        "accent": "#e1306c",
        "border": "#dbdbdb",
        "text": "#262626",
        "muted": "#8e8e8e"
      },
      "scale": 1,
      "x": 0,
      "y": 0,
      "fontSize": 65,
      "quoteMark": false,
      "parallax": true,
      "cinematicBarSize": 6,
      "backgroundOpacity": 10,
      "backgroundBlur": 12,
      "backgroundRadius": 42,
      "backgroundFeather": 84,
      "effects": [
        "dust",
        "bokeh"
      ]
    },
    {
      "id": "ig-pure-white",
      "label": "أبيض نقي",
      "description": "واجهة بيضاء نظيفة",
      "colors": {
        "background": "#ffffff",
        "card": "#ffffff",
        "accent": "#c13584",
        "border": "#e0e0e0",
        "text": "#1a1a1a",
        "muted": "#8a8a8a"
      },
      "scale": 1,
      "x": 0,
      "y": 0,
      "fontSize": 64,
      "quoteMark": false,
      "parallax": false,
      "cinematicBarSize": 8,
      "backgroundOpacity": 12,
      "backgroundBlur": 10,
      "backgroundRadius": 36,
      "backgroundFeather": 72,
      "effects": [
        "dust"
      ]
    }
  ],
  "points-broadcast": [
    {
      "id": "pb-classic-red",
      "label": "أحمر كلاسيكي",
      "description": "التصميم الكلاسيكي بالأحمر المباشر",
      "colors": {
        "background": "#d80b14",
        "backgroundAlt": "#b8050d",
        "text": "#ffffff",
        "accent": "#ffd21e"
      },
      "scale": 1,
      "x": 0,
      "y": 0,
      "fontSize": 65,
      "quoteMark": true,
      "parallax": true,
      "cinematicBarSize": 6,
      "backgroundOpacity": 10,
      "backgroundBlur": 12,
      "backgroundRadius": 42,
      "backgroundFeather": 84,
      "portraitScale": 1,
      "portraitX": 0,
      "portraitY": 0,
      "portraitMonochrome": true,
      "portraitSquare": false,
      "effects": [
        "dust",
        "bokeh"
      ]
    },
    {
      "id": "pb-dark-blue",
      "label": "أزرق رسمي",
      "description": "لون أزرق عميق لإطلالة رسمية",
      "colors": {
        "background": "#0a1628",
        "backgroundAlt": "#060e1a",
        "text": "#e8f0ff",
        "accent": "#4a90d9"
      },
      "scale": 0.95,
      "x": 0,
      "y": 0,
      "fontSize": 60,
      "quoteMark": true,
      "parallax": true,
      "cinematicBarSize": 6,
      "backgroundOpacity": 15,
      "backgroundBlur": 10,
      "backgroundRadius": 36,
      "backgroundFeather": 72,
      "portraitScale": 1,
      "portraitX": 0,
      "portraitY": 0,
      "portraitMonochrome": true,
      "portraitSquare": false,
      "effects": [
        "dust",
        "bokeh"
      ]
    },
    {
      "id": "pb-elegant-gold",
      "label": "ذهبي فخم",
      "description": "درجات ذهبية فاخرة على خلفية داكنة",
      "colors": {
        "background": "#1a1300",
        "backgroundAlt": "#0f0b00",
        "text": "#fff8e0",
        "accent": "#d4a843"
      },
      "scale": 1,
      "x": 0,
      "y": 0,
      "fontSize": 62,
      "quoteMark": true,
      "parallax": false,
      "cinematicBarSize": 8,
      "backgroundOpacity": 8,
      "backgroundBlur": 14,
      "backgroundRadius": 48,
      "backgroundFeather": 96,
      "portraitScale": 1,
      "portraitX": 0,
      "portraitY": 0,
      "portraitMonochrome": true,
      "portraitSquare": false,
      "effects": [
        "bokeh",
        "light-leak"
      ]
    }
  ],
  "sports-energy": [
    {
      "id": "se-field-green",
      "label": "أخضر ملعب",
      "description": "أخضر مستوحى من أرضية الملعب",
      "colors": {
        "background": "#0a140a",
        "surface": "#142014",
        "accent": "#4caf50",
        "accentAlt": "#66bb6a",
        "text": "#f5f5f5",
        "muted": "#9a9a9a"
      },
      "scale": 0.95,
      "x": 0,
      "y": 0,
      "fontSize": 62,
      "quoteMark": false,
      "parallax": false,
      "cinematicBarSize": 8,
      "backgroundOpacity": 12,
      "backgroundBlur": 14,
      "backgroundRadius": 48,
      "backgroundFeather": 96,
      "effects": [
        "bokeh"
      ]
    },
    {
      "id": "se-sports-red",
      "label": "أحمر رياضي",
      "description": "أحمر ناري للحماس الرياضي",
      "colors": {
        "background": "#0a0a0a",
        "surface": "#1a1a1a",
        "accent": "#e10600",
        "accentAlt": "#ff4422",
        "text": "#ffffff",
        "muted": "#b0b0b0"
      },
      "scale": 1.05,
      "x": 0,
      "y": 0,
      "fontSize": 68,
      "quoteMark": false,
      "parallax": true,
      "cinematicBarSize": 6,
      "backgroundOpacity": 8,
      "backgroundBlur": 10,
      "backgroundRadius": 36,
      "backgroundFeather": 72,
      "effects": [
        "dust",
        "light-leak"
      ]
    },
    {
      "id": "se-yellow-energy",
      "label": "أصفر حيوي",
      "description": "الطاقة والحيوية بالأصفر",
      "colors": {
        "background": "#0a0a0a",
        "surface": "#222222",
        "accent": "#f5d000",
        "accentAlt": "#e10600",
        "text": "#ffffff",
        "muted": "#cfcfcf"
      },
      "scale": 1,
      "x": 0,
      "y": 0,
      "fontSize": 65,
      "quoteMark": false,
      "parallax": true,
      "cinematicBarSize": 6,
      "backgroundOpacity": 10,
      "backgroundBlur": 12,
      "backgroundRadius": 42,
      "backgroundFeather": 84,
      "effects": [
        "dust",
        "light-leak",
        "bokeh"
      ]
    }
  ],
  "telegram-animated": [
    {
      "id": "tg-light-clean",
      "label": "فاتح",
      "description": "واجهة تلجرام الفاتحة",
      "colors": {
        "background": "#eef2f5",
        "header": "#ffffff",
        "card": "#ffffff",
        "accent": "#4f8ac9",
        "text": "#0a0a0a",
        "muted": "#707070"
      },
      "scale": 1,
      "x": 0,
      "y": 0,
      "fontSize": 65,
      "quoteMark": false,
      "parallax": true,
      "cinematicBarSize": 6,
      "backgroundOpacity": 12,
      "backgroundBlur": 10,
      "backgroundRadius": 36,
      "backgroundFeather": 72,
      "effects": [
        "dust"
      ]
    },
    {
      "id": "tg-night-mode",
      "label": "ليلي",
      "description": "وضع ليلي عميق",
      "colors": {
        "background": "#05080f",
        "header": "#0f1822",
        "card": "#111b26",
        "accent": "#6a9fd8",
        "text": "#e8eef4",
        "muted": "#6a7f94"
      },
      "scale": 0.95,
      "x": 0,
      "y": 0,
      "fontSize": 62,
      "quoteMark": false,
      "parallax": false,
      "cinematicBarSize": 8,
      "backgroundOpacity": 8,
      "backgroundBlur": 14,
      "backgroundRadius": 48,
      "backgroundFeather": 96,
      "effects": [
        "bokeh",
        "light-leak"
      ]
    },
    {
      "id": "tg-telegram-blue",
      "label": "أزرق تلجرام",
      "description": "أزرق تلجرام المميز",
      "colors": {
        "background": "#070b10",
        "header": "#17212b",
        "card": "#182533",
        "accent": "#5288c1",
        "text": "#ffffff",
        "muted": "#7f91a4"
      },
      "scale": 1,
      "x": 0,
      "y": 0,
      "fontSize": 65,
      "quoteMark": false,
      "parallax": true,
      "cinematicBarSize": 6,
      "backgroundOpacity": 10,
      "backgroundBlur": 12,
      "backgroundRadius": 42,
      "backgroundFeather": 84,
      "effects": [
        "dust",
        "bokeh"
      ]
    }
  ],
  "top-trends": [
    {
      "id": "tt-cyan-vibrant",
      "label": "سماوي حيوي",
      "description": "سماوي نابض بالحياة",
      "colors": {
        "background": "#09090e",
        "panel": "#161622",
        "accent": "#00f0ff",
        "accentAlt": "#ff0055",
        "text": "#ffffff",
        "muted": "#73738c"
      },
      "scale": 1,
      "x": 0,
      "y": 0,
      "fontSize": 65,
      "quoteMark": false,
      "parallax": true,
      "cinematicBarSize": 6,
      "backgroundOpacity": 10,
      "backgroundBlur": 12,
      "backgroundRadius": 42,
      "backgroundFeather": 84,
      "effects": [
        "dust",
        "bokeh",
        "light-leak"
      ]
    },
    {
      "id": "tt-dark-silver",
      "label": "داكن فضي",
      "description": "درجات فضية على خلفية داكنة",
      "colors": {
        "background": "#0a0a0f",
        "panel": "#18182a",
        "accent": "#c0c0d0",
        "accentAlt": "#8888aa",
        "text": "#f0f0f5",
        "muted": "#68687a"
      },
      "scale": 0.95,
      "x": 0,
      "y": 0,
      "fontSize": 62,
      "quoteMark": false,
      "parallax": false,
      "cinematicBarSize": 8,
      "backgroundOpacity": 12,
      "backgroundBlur": 14,
      "backgroundRadius": 48,
      "backgroundFeather": 96,
      "effects": [
        "bokeh"
      ]
    },
    {
      "id": "tt-hot-pink",
      "label": "وردي ناري",
      "description": "ألوان وردية جريئة",
      "colors": {
        "background": "#0e050a",
        "panel": "#1e0a14",
        "accent": "#ff2a6d",
        "accentAlt": "#ff6a00",
        "text": "#ffffff",
        "muted": "#a06070"
      },
      "scale": 1.05,
      "x": 0,
      "y": 0,
      "fontSize": 68,
      "quoteMark": false,
      "parallax": true,
      "cinematicBarSize": 6,
      "backgroundOpacity": 8,
      "backgroundBlur": 10,
      "backgroundRadius": 36,
      "backgroundFeather": 72,
      "effects": [
        "dust",
        "light-leak"
      ]
    }
  ],
  "x-animated": [
    {
      "id": "xa-dark-elegant",
      "label": "داكن أنيق",
      "description": "مظهر داكن بألوان ذهبية",
      "colors": {
        "background": "#000000",
        "card": "#141414",
        "accent": "#c09640",
        "border": "#2a2a2a",
        "text": "#f0ede8",
        "muted": "#8a8a8a"
      },
      "scale": 0.95,
      "x": 0,
      "y": 0,
      "fontSize": 62,
      "quoteMark": false,
      "parallax": false,
      "cinematicBarSize": 8,
      "backgroundOpacity": 8,
      "backgroundBlur": 14,
      "backgroundRadius": 48,
      "backgroundFeather": 96,
      "effects": [
        "bokeh",
        "light-leak"
      ]
    },
    {
      "id": "xa-light-mode",
      "label": "وضع فاتح",
      "description": "واجهة X الفاتحة النظيفة",
      "colors": {
        "background": "#e8ecf0",
        "card": "#ffffff",
        "accent": "#1d9bf0",
        "border": "#cfd6dd",
        "text": "#0f1419",
        "muted": "#536471"
      },
      "scale": 1,
      "x": 0,
      "y": 0,
      "fontSize": 65,
      "quoteMark": false,
      "parallax": true,
      "cinematicBarSize": 6,
      "backgroundOpacity": 12,
      "backgroundBlur": 10,
      "backgroundRadius": 36,
      "backgroundFeather": 72,
      "effects": [
        "dust"
      ]
    },
    {
      "id": "xa-twitter-blue",
      "label": "أزرق تويتر",
      "description": "أزرق X الكلاسيكي",
      "colors": {
        "background": "#000000",
        "card": "#192734",
        "accent": "#1d9bf0",
        "border": "#38444d",
        "text": "#ffffff",
        "muted": "#8899a6"
      },
      "scale": 1,
      "x": 0,
      "y": 0,
      "fontSize": 65,
      "quoteMark": false,
      "parallax": true,
      "cinematicBarSize": 6,
      "backgroundOpacity": 10,
      "backgroundBlur": 12,
      "backgroundRadius": 42,
      "backgroundFeather": 84,
      "effects": [
        "dust",
        "bokeh"
      ]
    }
  ]
};
